#Версия
version: "3"

services:
  #Внутри этой машины будет работать код на php
  api.php:
    build: ./backend/api_php

  #Внутри этой машины будут постоянные соединения (web socket)
  #(https://socket.io/docs/v4/redis-adapter/)
  api.node:
    build: ./backend/api_node

  #SQL база данных
  db.mysql:
    image: mysql
    ports:
      - "3306:3306"
    #Указываем файл с необходимыми параметрами для подключения
    env_file:
      - .env
    #Плохой вариант - писать переменные в этом файле
    environment:
      - SERVER_NAME=db.mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    env_file:
      - .env

  #InMemory  база данных
  db.redis:
    image: redis


  #Тип доступа в сеть
networks:
  itstep121azure:
    driver: bridge